# Generated by Django 4.0.4 on 2022-06-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='chicken', max_length=40),
            preserve_default=False,
        ),
    ]
