# Generated by Django 4.0.4 on 2022-05-18 22:51

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=phone_field.models.PhoneField(blank=True, help_text='Enter mobile number', max_length=31),
        ),
    ]
