# Generated by Django 4.0.4 on 2022-06-02 00:38

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_userprofile_avatar_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=225)),
                ('city_name', models.CharField(blank=True, max_length=225)),
                ('notes_for_address', models.TextField(blank=True)),
                ('mobile', phone_field.models.PhoneField(blank=True, help_text='Enter mobile number', max_length=31)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_info',
            field=models.ManyToManyField(to='userprofile.personalinfo'),
        ),
    ]
